[2025-01-04T13:36:31.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_currency_d manual__2025-01-04T13:26:16.393488+00:00 [queued]>
[2025-01-04T13:36:31.376+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_currency_d manual__2025-01-04T13:26:16.393488+00:00 [queued]>
[2025-01-04T13:36:31.376+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-01-04T13:36:31.389+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): md_currency_d> on 2025-01-04 13:26:16.393488+00:00
[2025-01-04T13:36:31.395+0000] {standard_task_runner.py:60} INFO - Started process 364 to run task
[2025-01-04T13:36:31.398+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_currency_d', 'manual__2025-01-04T13:26:16.393488+00:00', '--job-id', '1786', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpb0u2kbrm']
[2025-01-04T13:36:31.402+0000] {standard_task_runner.py:88} INFO - Job 1786: Subtask md_currency_d
[2025-01-04T13:36:31.458+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.md_currency_d manual__2025-01-04T13:26:16.393488+00:00 [running]> on host 8e43a3616b86
[2025-01-04T13:36:31.697+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_currency_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T13:26:16.393488+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T13:26:16.393488+00:00'
[2025-01-04T13:36:36.715+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/insert_data.py", line 36, in insert_data
    df['currency_code'] = df['currency_code'].astype(int).astype(str)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 105, in _astype_nansafe
    return _astype_float_to_int_nansafe(arr, dtype, copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 150, in _astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
[2025-01-04T13:36:36.728+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=insert_data, task_id=md_currency_d, execution_date=20250104T132616, start_date=20250104T133631, end_date=20250104T133636
[2025-01-04T13:36:36.743+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1786 for task md_currency_d (Cannot convert non-finite values (NA or inf) to integer; 364)
[2025-01-04T13:36:36.787+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-04T13:36:36.977+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
